#  To run: docker-compose -f docker-compose.local.yml up --build
version: '3'

services:
  gwsvc:
#    build: .
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - "8080:8080"
      - "80:80"
    env_file:
      - .env