name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-west-2"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Maven settings
        run: echo "<settings><servers><server><id>github-battre</id><username>${{ secrets.DEPENDENCY_USERNAME }}</username><password>${{ secrets.DEPENDENCY_PASSWORD }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Unit test with Maven
        run: mvn -B clean test

      - name: Report status to GitHub
        uses: myrotvorets/set-commit-status-action@master
        if: always() # Always report status even if there is a prior failure
        run: |
          STATUS=$(if [ ${{ job.status }} == success ]; then echo "success"; else echo "failure"; fi)
          PAYLOAD="{\"state\": \"$STATUS\", \"context\": \"CI Checks\", \"target_url\": \"${{ github.run_url }}\"}"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
                     -H "Accept: application/vnd.github+json" \
                     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     -H "X-GitHub-Api-Version: 2022-11-28" \
                     -d "$PAYLOAD" \
                     "https://api.github.com/repos/${{ github.repository }}/commits/${GITHUB_SHA}/statuses")
          if [[ $RESPONSE -ne 201 ]]; then
            echo "Failed to set commit status. HTTP status code: $RESPONSE"
            exit 1
          fi